version: '3.5'
services:
  postgres:
    image: postgres:14.4-alpine
    platform: linux/x86_64
    container_name: postgres_ktor_caching
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      PGUSER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'